language: node_js
sudo: false
node_js:
  - '8'
  - '10'
  - '11'

notifications:
  email:
    recipients:
    - ajax@bynder.com
    on_success: never
    on_failure: always

deploy:
  provider: npm
  email:
    secure: "k/orvp1twuGLoO8vpxVT9z06t/BVOlPV4i5+viu4F1V+PgLFO8c31NVimpf7i/71VhLivZAemaYAEHVG8l6HJ8FhuB7oJHMcXTrA8dvYNrueVF07Wz9tGIurMWtFdy8FATVdd4W3RMVYYRtpNtpX3HPKnpfNvQWyGsHyrBXsjP4yYZL33WNQ/SU5HqK1YJYw7ujvVNzC9G9VrgfDdkj/cclea3uo3CZzQbmStLf5FgrJ2y0ySZqYVofMPjgBFI5vLkn5hI8Pb/hkN1IvAeH4piWgHW8mNtQnrZaqR7jsY5jNH0dXRWuT4fjfUuY5L3wlO8ucFwndrbuxp+Zu07xc6VO3es8ZLz40suF+L53estUSYf3/E+zCof7hoL64couQ6VYNJgi+eho4e0baIqOHaHjjTvdyDdCvOulkgzY3YtmjnXZj/cdmPrP+XGTFGMpERlW6F6fMHljlnBYY2D+LvynRoFwbBH+Mol1I61SIR5F/Chd4HYA6GtNk6hO3lgoKkzwhvpSBN4OFurP2lUReZ19piTYBdsTLMyneTKQOzrWF7VSfGT41vJ6t0RrwoA4WYrHzzjchl57iFcxS45v+vr0xGFMAmy9IK/2fMABxF/gRs/PJUI6bx4bvdR2+oaCfhWe2LrLLRgYGki2MvbzPo8BxOd+6SxyjaINdjemAf5c="
  api_key:
    secure: "Xouzxsk9WYMxE0CRWEWYKcenoDwddduU9RopOp7GwYLPq38yxjAZURlz9u2dX4THwuyqrNuulOipFsrsW8qAFhLv6o2B3lGil/cPRroy3woli5Vy7TUJCwb4IQUOtxgU/ffgA5UKRJ2JFwz1K0F/dFegEbSq8CRzqKiKF2uZ/j/H1Tbym1FyvI/xuNXCQMhhew92X3nOdw2pWF009z8lafUwdGrwyau4CpFJHx6K5S/by+wFK/cR+HWW1RbFNpKQmWXJc5kdf4Z55L+HbMb/3gH780MoQeIAAeRACbGehx7wO5qGGDhxdiomLVZG0p63xOlMvVFMlGn434aHBmR8i/angWwDyLs9fiXvKWWXzY/IghxT6Or2e5ot4tgomX51WC0DYb6FScD9ZfadrNgV9sQtH/4AY5jUBWBQKzGJOw3JeAzM/jBIIIwupnFviUDZ8lItSNFiqx9fBa/XlpO1cu4vNKK2Swf9VVqi/gwlb9lLRKyO8tqeUfz0LMKe0pYS6iIrDjpP4tgpIcPfl2H2P5rWpNEqmvn99xu3X+8N0U564EurIQ4UmERZy+FLaPLY7M2PJMmRXVBk4hC6WRBrK68hx+lePhdFzJD51CRSqOfQObwILFa9erY90lZGUFN4FjUK8Un6Qgj8615Fe6W1nZb0M/Nv2+b/fM1NTo6d3Qs="
  on:
    tags: true
    repo: Bynder/bynder-js-sdk
  skip_cleanup: 'true'
